os: linux
dist : bionic

langage: python
python:
 - '3.8'

branches:
  only: 
    - master

before_install:
# Add NVIDIA package repositories
 - sudo apt install python
 - python --version
 - pip install -U pip
 - sudo apt install --yes gcc
 - wget https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/cuda-repo-ubuntu1804_10.1.243-1_amd64.deb
 - sudo apt-key adv --fetch-keys https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64/7fa2af80.pub
 - sudo dpkg -i cuda-repo-ubuntu1804_10.1.243-1_amd64.deb
 - sudo apt-get --yes update
 - wget http://developer.download.nvidia.com/compute/machine-learning/repos/ubuntu1804/x86_64/nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb
 - sudo apt --yes install  ./nvidia-machine-learning-repo-ubuntu1804_1.0.0-1_amd64.deb
 - sudo apt-get --yes update
# Install NVIDIA driver
 - sudo apt-get --yes install  --no-install-recommends nvidia-driver-430
 
install:
 - pip install tensorflow
 - pip install numpy
 - pip install matplotlib
 - pip install panda
# Install development and runtime libraries (~4GB)
 - sudo apt-get --yes install --no-install-recommends cuda-10-1 libcudnn7=7.6.4.38-1+cuda10.1 libcudnn7-dev=7.6.4.38-1+cuda10.1
# Install TensorRT. Requires that libcudnn7 is installed above.
 - sudo apt-get install -y --no-install-recommends libnvinfer6=6.0.1-1+cuda10.1 libnvinfer-dev=6.0.1-1+cuda10.1 libnvinfer-plugin6=6.0.1-1+cuda10.1

script:
 - echo "Passed"
